dati_principali<-data.frame(read.table("max_cles", header=TRUE, na.string="--"))
source("storage.R")
dati_gev<-storage(dati_principali,"N","N",2,9)
source("pearson.R")
dati_pearson<-pearson(dati_principali,dati_gev)
source("draw_peabel.R")
draw_peabel(dati_pearson,"N")
source("draw_lspp.R")
draw_lspp(dati_pearson,c(5,10,20,40,80),"N")
